[package]
name = "treeherder-dl"
description = "Download artifacts in bulk from Mozilla's TreeHerder"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ErichDonGubler/treeherder-dl"

[package.metadata.binstall]

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
env_logger = "0.10.0"
indicatif = "0.17.6"
log = "0.4.20"
regex = "1.9.4"
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["full"] }

[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.dist]
cargo-dist-version = "0.0.7"
rust-toolchain-version = "1.67.1"
ci = ["github"]
installers = ["shell", "powershell"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc", "aarch64-apple-darwin"]
