name: CI
on: [push]
jobs:
  cargo-clippy:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --locked -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --locked --release -- -D warnings

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          override: true
          profile: minimal
          toolchain: stable
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt --check

  cargo-test:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        toolchain:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --locked
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --locked

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          log-level: warn
          command: check
          arguments: --all-features
