name: CI (PR)

on: [pull_request]
jobs:
  block-autosquash-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Block merging fixup commits
        uses: ErichDonGubler/block-fixup-merge-action@patch-1
